r"""tests/test_r83_governed_proposal_handoff.py — R83: the terminal WITHHELD verdict
that no read surface could express.

THE DEFECT, as the live 2026-09-28 session recorded it.

The Portfolio Cycle ran and completed. Its ``BUILD_REALLOCATION_PROPOSAL`` step was
INVOKED, the economic gate had CLEARED (reassessment ``PROPOSAL_READY``), and
``api.reallocation_proposal`` built a complete alternative portfolio over 20 holdings,
re-optimised it under the breached limit and WITHHELD it: AMD 0.1503 and SNDK 0.1545
against the governed per-name risk-contribution cap 0.15. That is a COMPLETED,
fail-closed governed decision, and by the owner's own persistence contract it is never
written as an artifact (``STATE_WITHHELD_NOT_PERSISTABLE``).

Nothing downstream could say so. ``api.reallocation_proposal`` resolved its read state
from a PERSISTED artifact alone, so a session with no artifact always answered
``NOT_RUN`` — "the cycle never ran" — and, being the single source every other surface
composes, it made four surfaces lie at once:

  * Today                 PORTFOLIO PROPOSAL REQUESTED — NOT YET PRODUCED
  * Reallocation card     "the first proposal will be generated by the next completed
                          Daily Research Cycle", outstanding action
                          RUN_DAILY_RESEARCH_CYCLE
  * Decision review       "no proposal to review (read state NOT_RUN)",
                          NEXT REQUIRED ACTION = REFRESH THE REVIEW
  * Overview              "no feasible target was priced for this session"

Every one of those names an action that provably cannot change the verdict, and the
last one is false outright: a target WAS priced, and it cleared its economics
(+0.067127 net of cost) before a risk limit refused it.

``STATE_WITHHELD`` was declared in ``READ_STATE_VOCAB``, mapped by
``api.workflow_state`` to ``REALLOCATION_PROPOSAL_WITHHELD`` / "WITHHELD — PORTFOLIO
LIMITS", mapped by the canonical decision lane to ``CHANGE_CANDIDATE_WITHHELD`` / "NO
PROPOSAL — PORTFOLIO CHANGE WITHHELD", and policed by invariant I5. The entire
vocabulary was already in place and STRUCTURALLY UNREACHABLE, because the only state
source was a store that refuses to hold it. A declared state no store can produce is
not a state.

R83 closes the read seam: the governed run manifest — the ONE durable record of the
verdict — is consulted through the ONE canonical reference reader, and the verdict is
published VERBATIM. No second solver, no second index, no fabricated target, no
recomputed limit, and nothing becomes approvable.

EVERYTHING HERE IS HERMETIC. Every store root is a per-test ``tmp_path``. No network,
no provider, no prediction, no live store read on the paths under test, no Daily Close,
no operational-ledger write, no order / plan / fill, no approval, no selection, no
risk-policy ruling and no model promotion.
"""
from __future__ import annotations

from pathlib import Path

import pytest

from paper_trader.api import daily_action_gate as dag
from paper_trader.api import daily_research_cycle as drc
from paper_trader.api import portfolio_decision as pdec
from paper_trader.api import proposal_decision_review as pdr
from paper_trader.api import reallocation_proposal as rp
from paper_trader.api import workflow_state as ws
from paper_trader.engine import reallocation_proposal as rpk

# Reuse the verified deterministic harnesses (``tests`` is a package). The R74 harness
# runs a REAL Daily Research Cycle over a hermetic store with a withheld reallocation
# seam, so the manifest under test is one the production writer produced.
from tests.test_r74_withheld_terminal_contract import (  # noqa: E402
    WITHHELD_HASH, _manifest, _withheld_run)

BOOK = "alpha_paper_book_1"
SESSION = "2026-08-04"          # the harness's eligible completed session
OTHER_SESSION = "2026-08-03"
OTHER_BOOK = "alpha_paper_book_2"


# --------------------------------------------------------------------------- #
# Hermetic helpers.
# --------------------------------------------------------------------------- #
def _ps(*, book=BOOK, session=SESSION):
    """The minimum portfolio-state shape the read contract keys on."""
    return {"active_book": {"book_id": book, "book_label": book, "status": "ACTIVE",
                            "initialized": True, "holdings_count": 25},
            "dates": {"eligible_market_date": session}}


def _read(tmp, *, book=BOOK, session=SESSION):
    """The reallocation READ contract, bound to the hermetic stores only."""
    return rp.load_reallocation_proposal(portfolio_state=_ps(book=book, session=session),
                                         reallocation_dir=str(tmp / "realloc"),
                                         drc_dir=str(tmp))


def _summary(tmp, *, book=BOOK, session=SESSION):
    """The compact summary the gate -> workflow -> Today/Overview/Audit path uses."""
    return rp.load_proposal_summary(active_book_id=book, eligible_market_date=session,
                                    reallocation_dir=str(tmp / "realloc"),
                                    drc_dir=str(tmp))


def _card(tmp, *, reassessment_state="PROPOSAL_READY"):
    """The reallocation presentation card, fed exactly what the gate would forward."""
    s = _summary(tmp)
    return ws.build_reallocation_proposal_presentation(
        state=s["reallocation_proposal_state"],
        available=s["reallocation_proposal_available"],
        eligible_date=SESSION,
        action_counts=s["reallocation_action_counts"],
        proposal_hash=s["reallocation_proposal_hash"],
        proposed_holding_count=s["reallocation_proposed_holding_count"],
        one_way_turnover=s["reallocation_one_way_turnover"],
        estimated_transaction_cost=s["reallocation_estimated_transaction_cost"],
        cycle_complete=True, cycle_run_id="drc_test",
        reassessment_state=reassessment_state,
        withheld_outcome=s["reallocation_governed_withheld_outcome"])


def _decision(tmp, *, reassessment_state="PROPOSAL_READY"):
    """The ONE canonical portfolio-decision object the Today lane renders."""
    s = _summary(tmp)
    card = _card(tmp, reassessment_state=reassessment_state)
    return ws.build_canonical_portfolio_decision(
        reassessment_summary={"reassessment_state": reassessment_state,
                              "reassessment_available": True},
        reallocation_operator_state=card["canonical_operator_state"],
        portfolio_decision_lane={
            "reallocation_proposal_withheld": s["reallocation_proposal_withheld"],
            "withheld_reasons": s["reallocation_withheld_reasons"],
            "proposal_hash": s["reallocation_proposal_hash"]},
        attention_count=0, eligible_date=SESSION,
        withheld_outcome=s["reallocation_governed_withheld_outcome"])


def _review(tmp):
    """The Proposal Decision Review over the hermetic payload."""
    return pdr.load_proposal_decision_review(
        proposal_payload=_read(tmp), portfolio_state=_ps(),
        reallocation_dir=str(tmp / "realloc"), drc_dir=str(tmp),
        hoc_dir=str(tmp / "hoc"), outcome_dir=str(tmp / "out"),
        decision_dir=str(tmp / "dec"), latest_session=SESSION)


def _ready_result(*, hash_="ready_target_hash_r83", session=SESSION, book=BOOK):
    """A READY proposal in the kernel's own shape, for the success path."""
    return {
        "proposal_state": rpk.STATE_READY,
        "proposal_hash": hash_,
        "eligible_market_date": session,
        "active_book_id": book,
        "action_counts": {"RETAIN": 8, "INCREASE": 6, "REDUCE": 0, "EXIT": 11,
                          "ADD": 6, "REPLACE_OUT": 0, "REPLACE_IN": 0},
        "portfolio": {"proposed_holding_count": 20},
        "signal": {"score_improvement": 0.084627,
                   "score_improvement_net_of_cost": 0.067127},
        "turnover": {"one_way_turnover": 0.35, "estimated_transaction_cost": 85.97},
        "approvable": True,
        "withheld_reasons": [],
        "complete_target_limits": {"withheld": False, "all_ok": True},
        "data_gaps": [],
    }


def _persist_ready(tmp, **kw):
    return rp.persist_proposal(result=_ready_result(**kw),
                              input_contract={"active_book_id": kw.get("book", BOOK),
                                              "eligible_market_date": kw.get("session",
                                                                             SESSION)},
                              reallocation_dir=str(tmp / "realloc"))


def _artifacts(tmp):
    d = tmp / "realloc" / "artifacts"
    return sorted(p.name for p in d.glob("*.json")) if d.exists() else []


def _index(tmp):
    import json
    p = tmp / "realloc" / "index.json"
    return json.loads(p.read_text(encoding="utf-8")) if p.exists() else {}


# =========================================================================== #
# 1. THE PREMISE — why the state was unreachable at all.
# =========================================================================== #
def test_01_withheld_is_declared_in_the_read_vocabulary():
    assert rp.STATE_WITHHELD in rp.READ_STATE_VOCAB
    assert rp.STATE_WITHHELD == rpk.STATE_WITHHELD == drc.REALLOC_STATE_WITHHELD


def test_02_withheld_is_never_persistable_so_no_artifact_can_ever_carry_it(tmp_path):
    """The conjunction that made the state unreachable, asserted not assumed."""
    out = rp.persist_proposal(result={"proposal_state": rpk.STATE_WITHHELD},
                              input_contract={},
                              reallocation_dir=str(tmp_path / "realloc"))
    assert out["persisted"] is False and out["proposal_id"] is None
    assert out["reason"] == "STATE_WITHHELD_NOT_PERSISTABLE"
    assert rp.STATE_WITHHELD not in rp.APPROVABLE_READ_STATES
    assert _artifacts(tmp_path) == [] and _index(tmp_path) == {}


def test_03_the_downstream_withheld_vocabulary_already_existed():
    """R83 reaches a state four owners were already waiting for."""
    assert rp.STATE_WITHHELD in ws._RP_STATE_MAP
    assert ws._RP_STATE_MAP[rp.STATE_WITHHELD][0] == ws.RPS_WITHHELD
    assert ws.RPS_WITHHELD not in ws.REALLOCATION_APPROVABLE_STATES
    assert ws.CPD_CHANGE_WITHHELD in ws.CANONICAL_PORTFOLIO_DECISION_STATES
    assert ws.CPD_CHANGE_WITHHELD not in ws.CANONICAL_ACTIONABLE_DECISION_STATES


# =========================================================================== #
# 2. ONE PORTFOLIO CYCLE — the governed withheld lifecycle of 2026-09-28.
#    Assertions 1-13 of the acceptance contract.
# =========================================================================== #
def test_10_proposal_generation_is_invoked_and_completes(tmp_path):
    """(1) The handoff is NOT missing: the step runs and the owner rules."""
    r, _ = _withheld_run(tmp_path)
    step = next(s for s in r["step_results"]
                if s["step_id"] == drc.STEP_BUILD_REALLOCATION)
    assert step["status"] == drc.S_OK
    assert step["owner"] == "api.reallocation_proposal.run_and_persist"
    assert r["state"] == drc.COMPLETE and r["terminal"] is True
    assert r["reallocation_governed_outcome_complete"] is True


def test_11_a_withheld_verdict_persists_no_proposal_at_all(tmp_path):
    """(2) Exactly ZERO governed proposals exist — and that is the correct count."""
    _withheld_run(tmp_path)
    assert _artifacts(tmp_path) == []
    assert _index(tmp_path) == {}
    assert _read(tmp_path)["artifact"] is None
    assert _summary(tmp_path)["reallocation_proposal_id"] is None


def test_12_the_verdict_binds_the_exact_session_and_book(tmp_path):
    """(3)(4) Identity is proven, never assumed."""
    r, _ = _withheld_run(tmp_path)
    wh = rp.load_governed_withheld_outcome(active_book_id=BOOK,
                                          eligible_market_date=SESSION,
                                          drc_dir=str(tmp_path))
    assert wh is not None
    assert wh["active_book_id"] == BOOK == _manifest(tmp_path, r["run_id"])["active_book_id"]
    assert wh["eligible_market_date"] == SESSION
    assert wh["governed_run_id"] == r["run_id"]
    assert wh["proposal_hash"] == WITHHELD_HASH
    assert wh["proposal_id"] is None and wh["persisted"] is False


def test_13_the_read_contract_now_reaches_withheld_instead_of_not_run(tmp_path):
    """THE REGRESSION. This is the exact assertion that failed live on 2026-09-28."""
    _withheld_run(tmp_path)
    d = _read(tmp_path)
    assert d["state"] == rp.STATE_WITHHELD
    assert d["state"] != rp.STATE_NOT_RUN
    assert d["withheld"] is True
    assert d["approvable"] is False and d["executable"] is False
    assert d["withheld_reasons"] == [rpk.CT_RISK_CONTRIBUTION]
    assert d["governed_withheld_outcome"]["withheld_breaching_tickers"] == ["AMD", "DDOG"]
    # The futile instruction is gone from the sentence the operator reads.
    assert "Run the Daily Research Cycle" not in d["message"]
    assert "WITHHELD" in d["message"]


def test_14_the_summary_path_that_feeds_today_overview_and_audit_agrees(tmp_path):
    """(6)(7)(8) One source, so the three surfaces cannot disagree."""
    _withheld_run(tmp_path)
    s = _summary(tmp_path)
    assert s["reallocation_proposal_state"] == rp.STATE_WITHHELD
    assert s["reallocation_proposal_withheld"] is True
    assert s["reallocation_proposal_approvable"] is False
    # ``available`` keeps its ONE meaning: a PERSISTED proposal exists. It does not.
    assert s["reallocation_proposal_available"] is False
    assert s["reallocation_feasible_target_exists"] is False
    assert s["reallocation_governed_withheld_outcome"]["governed_outcome_complete"] is True


def test_15_the_gate_forwards_the_verdict_verbatim(tmp_path):
    """The shared path carries it; the gate decides nothing."""
    _withheld_run(tmp_path)
    s = _summary(tmp_path)
    assert "reallocation_governed_withheld_outcome" in s
    # The gate's forwarding list must name the field, or every surface above it
    # silently reverts to deriving "no proposal yet" from an absent artifact.
    src = Path(dag.__file__).read_text(encoding="utf-8")
    assert "reallocation_governed_withheld_outcome" in src


def test_16_the_reallocation_card_stops_naming_a_futile_action(tmp_path):
    """(9) R46.6.2's THIRD case: gate CLEARED, complete target withheld."""
    _withheld_run(tmp_path)
    c = _card(tmp_path)
    assert c["state"] == rp.STATE_WITHHELD
    assert c["canonical_operator_state"] == ws.RPS_WITHHELD
    assert c["complete_target_withheld_on_portfolio_limits"] is True
    assert c["running_the_cycle_again_would_change_nothing"] is True
    assert c["outstanding_action"] == "MANUAL_PORTFOLIO_CONSTRAINT_REVIEW"
    assert c["outstanding_action"] != "RUN_DAILY_RESEARCH_CYCLE"
    assert c["has_proposal"] is False and c["available"] is False
    assert "WITHHELD" in c["headline"]
    assert "next completed Daily Research Cycle" not in c["explanation"]
    assert c["withheld_breaching_tickers"] == ["AMD", "DDOG"]


def test_17_today_reports_the_withholding_not_a_missing_proposal(tmp_path):
    """(8) The headline that read PORTFOLIO PROPOSAL REQUESTED — NOT YET PRODUCED."""
    _withheld_run(tmp_path)
    d = _decision(tmp_path)
    assert d["state"] == ws.CPD_CHANGE_WITHHELD
    assert d["headline"] == "PORTFOLIO CHANGE WITHHELD"
    assert d["headline"] != "PORTFOLIO PROPOSAL REQUESTED — NOT YET PRODUCED"
    assert d["no_proposal_headline"] == "NO PROPOSAL — PORTFOLIO CHANGE WITHHELD"
    assert d["complete_target_withheld_on_portfolio_limits"] is True
    assert d["running_the_cycle_again_would_change_nothing"] is True


def test_18_today_does_not_call_a_risk_cap_breach_an_economic_failure(tmp_path):
    """R47's distinction, preserved. The target CLEARED its economics."""
    _withheld_run(tmp_path)
    reason = _decision(tmp_path)["no_proposal_reason"]
    assert "cleared its economics" in reason
    assert "no change cleared the economic hurdle" not in reason
    assert rpk.CT_RISK_CONTRIBUTION in reason
    assert "AMD" in reason and "DDOG" in reason
    assert "re-optimised" in reason


def test_19_the_decision_review_publishes_the_reason_and_the_next_act(tmp_path):
    """(5)(19)(20) The review is fail-closed AND informative."""
    _withheld_run(tmp_path)
    v = _review(tmp_path)
    # R74 coherence: these two ARE the correct answers for a withheld session and the
    # governed cycle's own verification gates on them. They must not change.
    assert v["status"] == pdr.STATUS_NO_PROPOSAL
    assert v["review_state"] == pdr.REVIEW_STATE_NO_PROPOSAL
    # What R83 adds: the reason, the verdict, and a next action that is not a loop.
    assert v["proposal_read_state"] == rp.STATE_WITHHELD
    assert v["governed_withheld_outcome"]["withheld"] is True
    assert v["next_required_action"] == "REVIEW_THE_WITHHELDING_PORTFOLIO_LIMIT"
    assert "RULED" in v["message"] and rpk.CT_RISK_CONTRIBUTION in v["message"]
    assert "read state NOT_RUN" not in v["message"]


def test_20_every_surface_names_the_same_next_act(tmp_path):
    """(9) The four surfaces converge on ONE outstanding action."""
    _withheld_run(tmp_path)
    card = _card(tmp_path)
    review = _review(tmp_path)
    s = _summary(tmp_path)
    wh = s["reallocation_governed_withheld_outcome"]
    # The card's vocabulary and the review's vocabulary differ by design (one is an
    # operator lane, one is a route contract) but BOTH must point at the limit review
    # and NEITHER may name a re-run or a refresh.
    assert card["outstanding_action"] == "MANUAL_PORTFOLIO_CONSTRAINT_REVIEW"
    assert review["next_required_action"] == wh["next_required_action"]
    for named in (card["outstanding_action"], review["next_required_action"]):
        assert "RUN_DAILY_RESEARCH_CYCLE" != named
        assert "REFRESH" not in named.upper()


def test_21_nothing_is_selected_approved_ruled_or_ordered(tmp_path):
    """(10)(11)(12)(13) The operator action firewall, asserted on the payloads."""
    _withheld_run(tmp_path)
    v = _review(tmp_path)
    assert not v.get("selection")
    assert v["actionable"] is False
    assert v["approval_available"] is False
    assert v["implementable_targets"] == []
    assert v["proposal_approvable"] is False
    assert not v.get("risk_policy_ruling")
    assert v["read_only"] is True and v["writes_nothing"] is True
    assert v["mutates_proposal"] is False
    # No store beyond the hermetic DRC manifest was created at all.
    for sub in ("realloc", "dec", "out"):
        assert not (tmp_path / sub).exists() or not any((tmp_path / sub).rglob("*.json"))


def test_22_a_withheld_target_can_never_be_exposed_as_approvable(tmp_path):
    """Invariant I5 — now reachable, and still holding."""
    _withheld_run(tmp_path)
    card = _card(tmp_path)
    assert card["canonical_operator_state"] == ws.RPS_WITHHELD
    assert card["execution_available"] is False
    assert card["creates_orders"] is False
    assert card["review_only"] is True
    assert _read(tmp_path)["approvable"] is False
    assert _summary(tmp_path)["reallocation_proposal_approvable"] is False


# =========================================================================== #
# 3. REPLAY — assertions 14-16.
# =========================================================================== #
def test_30_replaying_the_cycle_creates_no_second_proposal(tmp_path):
    """(14)(16) The withheld path has nothing to duplicate, and duplicates nothing."""
    r1, _ = _withheld_run(tmp_path)
    r2, _ = _withheld_run(tmp_path)
    assert r2["run_id"] == r1["run_id"]
    assert r2.get("reused_existing_run") or r2["state"] == drc.COMPLETE
    assert _artifacts(tmp_path) == []
    assert _index(tmp_path) == {}
    idx = drc._load_index(str(tmp_path))
    assert list(idx.keys()) == [SESSION]


def test_31_the_replayed_verdict_is_byte_identical(tmp_path):
    """(15) The same authoritative verdict is reused, never re-derived."""
    _withheld_run(tmp_path)
    first = rp.load_governed_withheld_outcome(
        active_book_id=BOOK, eligible_market_date=SESSION, drc_dir=str(tmp_path))
    _withheld_run(tmp_path)
    second = rp.load_governed_withheld_outcome(
        active_book_id=BOOK, eligible_market_date=SESSION, drc_dir=str(tmp_path))
    assert first == second
    assert _read(tmp_path)["state"] == rp.STATE_WITHHELD


def test_32_repeated_reads_never_mutate_anything(tmp_path):
    """(J) Refreshing is free and changes no authoritative state."""
    r, _ = _withheld_run(tmp_path)
    before = _manifest(tmp_path, r["run_id"])
    for _ in range(3):
        _read(tmp_path)
        _summary(tmp_path)
        _review(tmp_path)
    assert _manifest(tmp_path, r["run_id"]) == before
    assert _artifacts(tmp_path) == []


# =========================================================================== #
# 4. THE SUCCESS PATH — a produced proposal still resolves, exactly once.
# =========================================================================== #
def test_40_a_ready_proposal_persists_once_and_the_index_resolves_it(tmp_path):
    """(2)(3)(4) for the path where the owner DOES produce a proposal."""
    out = _persist_ready(tmp_path)
    assert out["persisted"] is True and out["proposal_id"]
    assert len(_artifacts(tmp_path)) == 1
    assert len(_index(tmp_path)) == 1
    d = _read(tmp_path)
    assert d["state"] == rp.STATE_READY
    assert d["artifact"]["proposal_id"] == out["proposal_id"]
    assert d["eligible_market_date"] == SESSION


def test_41_persisting_the_same_proposal_again_does_not_duplicate_it(tmp_path):
    """(14) Idempotency on the produced path."""
    first = _persist_ready(tmp_path)
    again = _persist_ready(tmp_path)
    assert again["proposal_id"] == first["proposal_id"]
    assert again.get("reused") is True or again["persisted"] is False
    assert len(_artifacts(tmp_path)) == 1
    assert len(_index(tmp_path)) == 1


def test_42_a_persisted_proposal_outranks_a_manifest_verdict(tmp_path):
    """The governed-manifest consult is NOT a fallback that can shadow an artifact."""
    _withheld_run(tmp_path)
    _persist_ready(tmp_path)
    d = _read(tmp_path)
    assert d["state"] == rp.STATE_READY
    assert d["governed_withheld_outcome"] is None
    assert _summary(tmp_path)["reallocation_proposal_state"] == rp.STATE_READY


# =========================================================================== #
# 5. FAIL-CLOSED — every absence that must STAY NOT_RUN. Assertions 17-19.
# =========================================================================== #
def test_50_no_manifest_still_reports_not_run(tmp_path):
    """(17) Unchanged behaviour where nothing has happened."""
    d = _read(tmp_path)
    assert d["state"] == rp.STATE_NOT_RUN
    assert d["withheld"] is False
    assert d["governed_withheld_outcome"] is None
    assert "Run the Daily Research Cycle" in d["message"]
    assert _summary(tmp_path)["reallocation_proposal_state"] == rp.STATE_NOT_RUN


def test_51_a_non_terminal_run_is_never_published_as_a_verdict(tmp_path):
    """(18) An unfinished run is not a ruling. Fail closed."""
    r, _ = _withheld_run(tmp_path)
    rec = _manifest(tmp_path, r["run_id"])
    rec["state"] = "IN_PROGRESS"
    drc._save_run(rec, str(tmp_path))
    drc._update_index(eligible_date=SESSION, idempotency_key=rec["idempotency_key"],
                      input_contract_hash=rec["input_contract_hash"],
                      run_id=r["run_id"], state="IN_PROGRESS", drc_dir=str(tmp_path))
    assert rp.load_governed_withheld_outcome(
        active_book_id=BOOK, eligible_market_date=SESSION, drc_dir=str(tmp_path)) is None
    assert _read(tmp_path)["state"] == rp.STATE_NOT_RUN


def test_52_an_incomplete_governed_outcome_is_never_published(tmp_path):
    """A WITHHELD state without a COMPLETE outcome is not a settled verdict."""
    r, _ = _withheld_run(tmp_path)
    rec = _manifest(tmp_path, r["run_id"])
    rec["reallocation_governed_outcome_complete"] = False
    drc._save_run(rec, str(tmp_path))
    assert rp.load_governed_withheld_outcome(
        active_book_id=BOOK, eligible_market_date=SESSION, drc_dir=str(tmp_path)) is None
    assert _read(tmp_path)["state"] == rp.STATE_NOT_RUN


def test_53_another_books_verdict_is_never_borrowed(tmp_path):
    _withheld_run(tmp_path)
    assert rp.load_governed_withheld_outcome(
        active_book_id=OTHER_BOOK, eligible_market_date=SESSION,
        drc_dir=str(tmp_path)) is None
    assert _read(tmp_path, book=OTHER_BOOK)["state"] == rp.STATE_NOT_RUN


def test_54_another_sessions_verdict_is_never_borrowed(tmp_path):
    _withheld_run(tmp_path)
    assert rp.load_governed_withheld_outcome(
        active_book_id=BOOK, eligible_market_date=OTHER_SESSION,
        drc_dir=str(tmp_path)) is None
    assert _read(tmp_path, session=OTHER_SESSION)["state"] == rp.STATE_NOT_RUN


def test_55_a_non_withheld_governed_state_publishes_no_verdict(tmp_path):
    """Only WITHHELD resolves this way; READY/BLOCKED never synthesise a target."""
    r, _ = _withheld_run(tmp_path)
    rec = _manifest(tmp_path, r["run_id"])
    rec["reallocation_proposal_state"] = "BLOCKED"
    drc._save_run(rec, str(tmp_path))
    assert rp.load_governed_withheld_outcome(
        active_book_id=BOOK, eligible_market_date=SESSION, drc_dir=str(tmp_path)) is None


def test_56_a_missing_identity_is_refused_not_assumed(tmp_path):
    """A manifest that predates the book field cannot prove its binding."""
    r, _ = _withheld_run(tmp_path)
    rec = _manifest(tmp_path, r["run_id"])
    rec.pop("active_book_id", None)
    drc._save_run(rec, str(tmp_path))
    assert rp.load_governed_withheld_outcome(
        active_book_id=BOOK, eligible_market_date=SESSION, drc_dir=str(tmp_path)) is None


def test_57_a_withheld_verdict_never_fabricates_a_target(tmp_path):
    """(no fabrication) The verdict carries economics, never weights or allocations."""
    _withheld_run(tmp_path)
    d = _read(tmp_path)
    assert d["allocations"] == []
    assert d["portfolio"] == {}
    assert d["artifact"] is None
    wh = d["governed_withheld_outcome"]
    assert "allocations" not in wh and "weights" not in wh
    # The economics it DOES publish are the owner's own measured numbers.
    assert wh["one_way_turnover"] == 0.35
    assert wh["proposed_holding_count"] == 20


# =========================================================================== #
# 6. HERMETIC ISOLATION — the consult must never reach a live store.
# =========================================================================== #
def test_60_a_proposal_only_redirect_never_consults_the_governed_manifest(tmp_path):
    """The SAME rule the supersession verdict uses. A test that redirected only the
    proposal store must keep its constructed world, and must never open the live
    research store to answer a question about it."""
    assert rp._should_consult_governed_manifest(
        reallocation_dir=str(tmp_path), drc_dir=None) is False
    assert rp._should_consult_governed_manifest(
        reallocation_dir=str(tmp_path), drc_dir=str(tmp_path)) is True
    assert rp._should_consult_governed_manifest(
        reallocation_dir=None, drc_dir=None) is True
    # Proven behaviourally: a withheld manifest exists, and a proposal-only redirect
    # does not see it.
    _withheld_run(tmp_path)
    blind = rp.load_reallocation_proposal(portfolio_state=_ps(),
                                          reallocation_dir=str(tmp_path / "realloc"))
    assert blind["state"] == rp.STATE_NOT_RUN
    assert rp.load_proposal_summary(
        active_book_id=BOOK, eligible_market_date=SESSION,
        reallocation_dir=str(tmp_path / "realloc"),
    )["reallocation_proposal_state"] == rp.STATE_NOT_RUN


def test_61_the_resolver_degrades_and_never_raises(tmp_path):
    """A read must never crash its caller on a missing or broken store."""
    assert rp.load_governed_withheld_outcome(
        active_book_id=BOOK, eligible_market_date=SESSION,
        drc_dir=str(tmp_path / "does_not_exist")) is None
    assert rp.load_governed_withheld_outcome(
        active_book_id=None, eligible_market_date=SESSION, drc_dir=str(tmp_path)) is None
    assert rp.load_governed_withheld_outcome(
        active_book_id=BOOK, eligible_market_date=None, drc_dir=str(tmp_path)) is None
    bad = tmp_path / "bad"
    bad.mkdir()
    (bad / "index.json").write_text("{not json", encoding="utf-8")
    assert rp.load_governed_withheld_outcome(
        active_book_id=BOOK, eligible_market_date=SESSION, drc_dir=str(bad)) is None


def test_62_the_manifest_reference_forwards_the_verdict_without_deriving_it(tmp_path):
    """The canonical reference reader stays a pass-through file read."""
    r, _ = _withheld_run(tmp_path)
    ref = drc.load_governed_manifest_reference(eligible_market_date=SESSION,
                                               drc_dir=str(tmp_path))
    rec = _manifest(tmp_path, r["run_id"])
    for field in ("reallocation_proposal_state", "reallocation_withheld_codes",
                  "reallocation_withheld_breaching_tickers",
                  "reallocation_governed_outcome_complete",
                  "reallocation_one_way_turnover", "reallocation_proposed_holding_count",
                  "active_book_id"):
        assert ref[field] == rec[field], field
    assert ref["owner"] == "api.daily_research_cycle"


# =========================================================================== #
# 7. THE SAME UNREACHABLE-STATE DEFECT, ONE AND TWO LAYERS UP.
#
#    ``PDS_CHANGE_WITHHELD`` sat behind ``available`` — a term that means "a PERSISTED
#    artifact exists" and that a withheld verdict can never satisfy — so every withheld
#    session reached ``PDS_NO_PROPOSAL``. The reassessment card's own suppression keys
#    on that state, which is why it kept offering REVIEW PORTFOLIO PROPOSAL over a
#    change the governed owner had already refused, under the title PORTFOLIO PROPOSAL
#    READY.
# =========================================================================== #
def _lane(*, withheld, available, reasons=None):
    return pdec.derive_decision_state(
        has_active_book=True,
        proposal_summary={"reallocation_proposal_available": available,
                          "reallocation_proposal_withheld": withheld,
                          "reallocation_withheld_reasons": reasons or [],
                          "reallocation_proposal_hash": WITHHELD_HASH},
        decision_record=None)


def test_70_a_withheld_verdict_without_an_artifact_reaches_change_withheld():
    """THE REGRESSION one layer up."""
    lane = _lane(withheld=True, available=False,
                 reasons=[rpk.CT_RISK_CONTRIBUTION])
    assert lane["portfolio_decision_state"] == pdec.PDS_CHANGE_WITHHELD
    assert lane["portfolio_decision_state"] != pdec.PDS_NO_PROPOSAL
    assert lane["approvable"] is False


def test_71_a_genuine_absence_still_reaches_no_proposal():
    """The narrowing: only a WITHHELD verdict takes the new path."""
    lane = _lane(withheld=False, available=False)
    assert lane["portfolio_decision_state"] == pdec.PDS_NO_PROPOSAL
    assert lane["approvable"] is False


def test_72_change_withheld_is_never_approvable():
    assert pdec.PDS_CHANGE_WITHHELD not in pdec.APPROVABLE_DECISION_STATES
    lane = _lane(withheld=True, available=False)
    assert lane["approvable"] is False
    assert lane.get("executable") in (False, None)


def test_73_the_assessment_card_stops_promising_a_proposal_that_cannot_exist():
    """(B) AUDIT & DETAILS must not read PROPOSAL_READY as proposal existence."""
    from paper_trader.api import portfolio_reassessment as prs
    pres = prs.build_presentation(
        state=prs.STATE_PROPOSAL_READY,
        reassessment={"decision": {}, "attention": {"count": 3}},
        decision_lane={"portfolio_decision_state": pdec.PDS_CHANGE_WITHHELD})
    # The reassessment's OWN verdict is untouched — it really did ask for a target.
    assert pres["state"] == prs.STATE_PROPOSAL_READY
    # What changes is every claim about the DOWNSTREAM result.
    assert pres["title"] == "PORTFOLIO CHANGE WITHHELD — PROPOSAL NOT PRODUCED"
    assert pres["title"] != "PORTFOLIO PROPOSAL READY"
    assert pres["primary_action"] is None
    assert pres["proposal_exists"] is False
    assert pres["requested_proposal_was_withheld"] is True
    # An unresolved MANDATORY limit is not a success and is not "no action required".
    assert pres["severity"] == "ATTENTION"
    assert pres["next_action"] == "REVIEW THE PORTFOLIO LIMIT THAT WITHHELD THE CHANGE"
    assert "No action required" not in pres["next_action"]


def test_74_a_settled_hold_keeps_its_benign_wording():
    """The narrowing again: HOLD and NO_MATERIAL_CHANGE really are closed questions."""
    from paper_trader.api import portfolio_reassessment as prs
    for lane_state in ("HOLD_CURRENT_BOOK", "NO_MATERIAL_CHANGE"):
        pres = prs.build_presentation(
            state=prs.STATE_PROPOSAL_READY, reassessment={"decision": {}},
            decision_lane={"portfolio_decision_state": lane_state})
        assert pres["severity"] == "SUCCESS", lane_state
        assert pres["next_action"] == "No action required — the governed decision stands"
        assert pres["title"] == "PORTFOLIO PROPOSAL READY"
        assert pres["requested_proposal_was_withheld"] is False


def test_75_the_overview_envelope_carries_the_verdict(tmp_path):
    """(C) The Portfolio Overview reads the SAME verdict, from the same owner."""
    _withheld_run(tmp_path)
    env = rp.load_constrained_reallocation(
        portfolio_state=_ps(), reallocation_dir=str(tmp_path / "realloc"),
        drc_dir=str(tmp_path), decision_dir=str(tmp_path / "dec"),
        include_execution=False)
    assert env["state"] == rp.STATE_WITHHELD
    assert env["complete_target_withheld_on_portfolio_limits"] is True
    wh = env["governed_withheld_outcome"]
    assert wh["withheld_breaching_tickers"] == ["AMD", "DDOG"]
    assert wh["next_required_action"] == "REVIEW_THE_WITHHELDING_PORTFOLIO_LIMIT"
    assert env["headline"] == ("COMPLETE TARGET WITHHELD - PORTFOLIO LIMIT REVIEW "
                              "REQUIRED")
    assert "RUN THE DAILY RESEARCH CYCLE" not in env["headline"]
    # No target is fabricated for the Overview's target column.
    assert env["best_feasible_target"]["weights"] == {}
    assert env["feasible_target_exists"] is not True


# =========================================================================== #
# 8. THE BROWSER — it RENDERS the verdict and DERIVES none of it.
#
#    Assertion 20 of the acceptance contract, and the R82.2 rule applied to a second
#    verdict: every affordance and every next-action label reads ONE published field.
# =========================================================================== #
UI = Path(__file__).resolve().parent.parent / "api" / "ui" / "index.html"


def _ui_src():
    return UI.read_text(encoding="utf-8", errors="replace")


def _ui_fn(src, name, end_marker):
    start = src.find("function " + name)
    assert start != -1, name
    end = src.find(end_marker, start)
    assert end != -1, end_marker
    return src[start:end]


def test_80_the_status_bar_reads_the_published_verdict():
    bar = _ui_fn(_ui_src(), "_pdrStatusBar", "_pdrStaleExplainer")
    assert "d.governed_withheld_outcome" in bar
    assert "wh.next_required_action" in bar
    assert "wh.approval_withheld_because" in bar
    # R82.2's gate contract is untouched — the withheld path is an ADDITIONAL
    # backend-owned source, never a replacement.
    assert "d.approval_gate" in bar
    assert "g.next_required_action_label" in bar


def test_81_the_browser_derives_no_limit_code_ticker_or_excess():
    """The verdict's substance is never recomputed in the browser."""
    src = _ui_src()
    for fn, end in (("_pdrStatusBar", "_pdrStaleExplainer"),
                    ("_r47Render", "window._r47Render")):
        body = _ui_fn(src, fn, end)
        # No cap arithmetic, no threshold comparison against a hard-coded limit.
        assert "0.15" not in body, fn
        assert "RISK_CONTRIBUTION_CAP" not in body, fn
        assert "excess" not in body or ".excess" not in body.replace("b.excess", ""), fn


def test_82_no_surface_spells_a_refresh_as_the_act_over_a_settled_verdict():
    """The exact defect: REFRESH THE REVIEW was published as the next act."""
    bar = _ui_fn(_ui_src(), "_pdrStatusBar", "_pdrStaleExplainer")
    # The stated-unknown fallback survives (an unreadable review IS unknown), but it
    # must be guarded by ``known`` and must not be reachable when a verdict exists.
    assert "REFRESH THE REVIEW" in bar
    idx_wh = bar.find("wh.next_required_action")
    idx_refresh = bar.find("'REFRESH THE REVIEW'")
    assert idx_wh < idx_refresh, "the verdict must be consulted before the fallback"


def test_84_the_today_hero_does_not_answer_no_action_over_an_unresolved_limit():
    """(9) The Today hero collapsed CHANGE_WITHHELD into a green HOLD with NO ACTION
    NOW, while three other surfaces named reviewing the limit as the outstanding act."""
    from paper_trader.api import operator_presentation as op
    cpd = {"state": ws.CPD_CHANGE_WITHHELD,
           "complete_target_withheld_on_portfolio_limits": True,
           "no_proposal_reason": "a governed portfolio LIMIT refused it",
           "withheld_reasons": [rpk.CT_RISK_CONTRIBUTION]}
    pd = op._portfolio_decision({"canonical_portfolio_decision": cpd}, {}, {},
                                {"historical": False})
    assert pd["tone"] == "warn", "an unresolved mandatory limit is not a green hold"
    assert "WITHHELD" in pd["headline"]
    assert pd["headline"] != "HOLD CURRENT PORTFOLIO"
    na = pd.get("next_action") or {}
    assert na.get("available") is True
    # Navigation only — a withheld verdict raises no execution affordance at all.
    assert na.get("kind") == op.NA_REVIEW_REALLOCATION
    assert na.get("navigates") is True and na.get("executes") is False
    assert na.get("creates_orders") is False and na.get("approves_anything") is False
    assert na.get("execution_contract") is None
    assert pd["creates_orders"] is False and pd["automation_off"] is True


def test_85_an_economic_withholding_keeps_its_existing_quiet_words():
    """The narrowing: only a PORTFOLIO-LIMIT withholding takes the new branch."""
    from paper_trader.api import operator_presentation as op
    cpd = {"state": ws.CPD_CHANGE_WITHHELD,
           "complete_target_withheld_on_portfolio_limits": False,
           "no_proposal_reason": "no change cleared the economic hurdle"}
    pd = op._portfolio_decision({"canonical_portfolio_decision": cpd}, {}, {},
                                {"historical": False})
    assert pd["headline"] == "HOLD CURRENT PORTFOLIO"
    assert pd["tone"] == "ok"
    assert (pd.get("next_action") or {}).get("available") is False


def test_83_no_alert_or_confirm_was_introduced():
    """CLAUDE.md hard-failure conditions, checked on the changed file."""
    src = _ui_src()
    for pat in ("alert(", "confirm("):
        for line in src.splitlines():
            s = line.strip()
            if pat in s and not s.startswith("//") and not s.startswith("*"):
                # The only permitted spellings are non-dialog identifiers.
                assert ("window.alert(" not in s and "window.confirm(" not in s), s
                assert not s.lstrip().startswith(pat), s
