"""
alpha_agent.fundamental_jobs — Stage 10.2 CANONICAL FUNDAMENTAL JOBS + PLANNER.

The reusable capability the AlphaAgent needs to OPERATE the downstream path from
the released historical identity layer (Stage 10.1) to real survivorship-safe
historical PIT fundamental evaluation, through the SAME durable ``ResearchQueue``
and one-job-per-cycle fair scheduler — Claude builds the capability; the
AlphaAgent prioritizes, creates, claims and executes the jobs and (when the
measured activation gate opens) generates + runs the fundamental experiment.

A distinct Stage 10.2 campaign (origin ``stage10.2-fundamentals``, the new
allowlisted ``fundamentals.`` lane prefix) that reuses EXACTLY the existing
infrastructure: the durable ``CampaignStore`` (mapped-CIK cursor + append-only
supersession), the ``BulkArchiveDownloader`` (resumable/atomic/SHA-256), the new
``SecCompanyFactsIndex`` (durable bulk companyfacts index), the ``PitFundamentals
Store`` (leakage-safe PIT view) and the measured ``fundamental_readiness``
contract. Every job is BOUNDED, IDEMPOTENT, RESTART-SAFE, FAILURE-ISOLATED,
DEDUPLICATED and CONFIG-CONTROLLED; completion flags are stamped by the HANDLER
on success (never at plan time) so a failed step re-runs and none is silently
skipped. No second worker/queue/scheduler.

Lanes (all origin ``stage10.2-fundamentals``, prefix ``fundamentals.``):
  * fundamentals.bulk_inventory   (DATA_ACQUISITION) — inventory owned facts +
    DOWNLOAD companyfacts.zip (restart-safe/atomic/SHA-256).
  * fundamentals.mapped_cik_plan  (DATA_ACQUISITION) — derive the resolved
    historical CIK target set + seed/supersede the durable campaign cursor.
  * fundamentals.bulk_index       (DATA_ACQUISITION) — stream companyfacts.zip
    into the durable fact index: catalogue every member, materialise the target
    concepts for the mapped CIKs; record per-CIK campaign progress.
  * fundamentals.pit_materialize  (DATA_VALIDATION) — build the leakage-safe PIT
    store from the index for the mapped CIKs; measure observations + concepts.
  * fundamentals.coverage_measure (DATA_VALIDATION) — per-rebalance PIT readiness
    for every candidate on the survivorship-safe historical universe.
  * fundamentals.readiness_recheck(DATA_VALIDATION) — measured mapping + measured
    readiness + the measured activation gate (never flips a switch).
  * fundamentals.activation_recheck(DATA_VALIDATION) — record the final measured
    activation-gate result. The experiment itself is generated by the tournament
    tick when the gate opens — never enqueued here.

Pure stdlib; deterministic; the only side effects are the durable companyfacts
index, the durable campaign cursor, immutable artifacts and enqueues into the
shared research queue. No operational-ledger / order / fill / signal / trade-
decision / model-promotion / prediction touch anywhere.
"""
from __future__ import annotations

import json
from dataclasses import dataclass, field
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Callable, Optional

from . import historical_identity as _hi
from .identity_jobs import write_artifact

ORIGIN_102 = "stage10.2-fundamentals"
FUNDAMENTAL_LANE_PREFIX = "fundamentals."

LANE_FUND_BULK_INVENTORY = "fundamentals.bulk_inventory"
LANE_FUND_MAPPED_CIK_PLAN = "fundamentals.mapped_cik_plan"
LANE_FUND_BULK_INDEX = "fundamentals.bulk_index"
LANE_FUND_PIT_MATERIALIZE = "fundamentals.pit_materialize"
LANE_FUND_COVERAGE_MEASURE = "fundamentals.coverage_measure"
LANE_FUND_READINESS_RECHECK = "fundamentals.readiness_recheck"
LANE_FUND_ACTIVATION_RECHECK = "fundamentals.activation_recheck"

_ACQUISITION_LANES = frozenset({
    LANE_FUND_BULK_INVENTORY, LANE_FUND_MAPPED_CIK_PLAN, LANE_FUND_BULK_INDEX})
_VALIDATION_LANES = frozenset({
    LANE_FUND_PIT_MATERIALIZE, LANE_FUND_COVERAGE_MEASURE,
    LANE_FUND_READINESS_RECHECK, LANE_FUND_ACTIVATION_RECHECK})

DEFAULT_PRIORITY = 4   # below the identity backlog (6) and companyfacts bootstrap
#                        (5): the historical identity bridge + current-universe
#                        companyfacts continuation keep precedence; this downstream
#                        campaign runs after, and its finite backlog can never
#                        permanently starve the tournament.
DEFAULT_CAMPAIGN_ID = "sec_companyfacts_historical"
CAMPAIGN_KIND = "fund.stage10_2"
DEFAULT_SIGNALS = ("gross_profitability", "asset_growth", "balance_sheet_quality")


def _utc_now_iso() -> str:
    return datetime.now(timezone.utc).replace(microsecond=0).isoformat()


# --------------------------------------------------------------------------- #
# Fundamental job context (all heavy dependencies injected for testability).
# --------------------------------------------------------------------------- #
@dataclass
class FundamentalJobContext:
    store: _hi.IdentityStore                     # the Stage 10 identity store
    companyfacts_index: Any                      # SecCompanyFactsIndex
    campaign_store: Any                          # acquisition_campaign.CampaignStore
    artifact_root: str
    rebalance_dates: "list[str]" = field(default_factory=list)
    cfg9: dict = field(default_factory=dict)
    stage102: dict = field(default_factory=dict)  # the stage10_2 config block
    index_name: str = "S&P 500"
    signals: "tuple" = DEFAULT_SIGNALS
    transport: Optional[Callable] = None
    read_normalized: Optional[Callable] = None
    clock: Optional[Callable[[], str]] = None

    def now(self) -> str:
        return (self.clock or _utc_now_iso)()


def _outcomes():
    from . import autonomous_research as _ar
    return (_ar.OUTCOME_COMPLETED, _ar.OUTCOME_BLOCKED_SPECIFIC,
            _ar.OUTCOME_RETRYABLE)


# --------------------------------------------------------------------------- #
# Config / provenance helpers.
# --------------------------------------------------------------------------- #
def _cfg(ctx: FundamentalJobContext) -> dict:
    return ctx.stage102 or {}


def _ua_headers(cfg: dict) -> dict:
    ua = "%s %s" % (cfg.get("user_agent_product",
                            "paper-trader-alpha-agent/2.0"),
                    cfg.get("contact_email") or "")
    return {"User-Agent": ua.strip(), "Accept-Encoding": "identity"}


def _companyfacts_paths(cfg: dict):
    root = cfg.get("bulk_root")
    if not root:
        return None, None
    return (Path(root) / "companyfacts.zip",
            Path(root) / "companyfacts.manifest.json")


def _companyfacts_hash(cfg: dict) -> Optional[str]:
    _, manifest = _companyfacts_paths(cfg)
    if manifest and manifest.exists():
        try:
            return json.loads(manifest.read_text(encoding="utf-8")).get("sha256")
        except (OSError, ValueError):
            return None
    return None


def _resolved_ciks(ctx: FundamentalJobContext) -> list:
    """Every canonical CIK with an ACTIVE RESOLVED mapping (the survivorship-safe
    historical universe — current + delisted). Deterministic sorted set."""
    out = []
    for s in ctx.store.list_securities(limit=1000000):
        mp = ctx.store.active_mapping(s["security_id"])
        if mp and mp.get("status") == _hi.STATUS_RESOLVED and mp.get("cik"):
            out.append(_hi.norm_cik(mp["cik"]))
    return sorted({c for c in out if c})


def _mapping_version(ctx: FundamentalJobContext) -> str:
    return (ctx.store.get_meta("stage101_mapping_version_hash")
            or ctx.store.get_meta("stage102_mapped_epoch") or "nomvh")


def _epoch(ctx: FundamentalJobContext) -> str:
    """A CHEAP, stable epoch key = (identity mapping-version, companyfacts archive
    hash). It changes only when the resolved mapping OR the owned archive genuinely
    changes, so each downstream measurement runs exactly once per epoch and
    re-runs honestly when the underlying evidence changes."""
    mvh = str(_mapping_version(ctx))[:12]
    ah = str(_companyfacts_hash(_cfg(ctx)) or "noarch")[:12]
    return "%s:%s" % (mvh, ah)


def _target_tags(ctx: FundamentalJobContext):
    from . import sec_companyfacts_index as _cfi
    return _cfi.default_target_tags()


# --------------------------------------------------------------------------- #
# Per-lane handlers. Each is bounded, idempotent, restart-safe and returns
# (outcome, detail) with an immutable artifact path or an exact blocker.
# --------------------------------------------------------------------------- #
def _fund_bulk_inventory(ctx: FundamentalJobContext, job) -> tuple:
    """Part 1: inventory the owned companyfacts + DOWNLOAD the companyfacts bulk
    archive with the existing restart-safe/atomic/SHA-256 downloader (looped to
    completion inside a wall-clock budget; a transport interruption is RETRYABLE
    and resumes from the durable byte checkpoint). No parsing here."""
    import time as _time
    from . import sec_bulk_download as _bulk
    OK, BLK, RETRY = _outcomes()
    cfg = _cfg(ctx)
    final, manifest = _companyfacts_paths(cfg)
    url = cfg.get("companyfacts_url")
    if final is None or not url:
        return BLK, {"real_work": LANE_FUND_BULK_INVENTORY,
                     "blocker": "STAGE102_NOT_CONFIGURED",
                     "reason": "bulk_root/companyfacts_url not configured",
                     "disposition": "DATA_HOLD"}
    if ctx.transport is None:
        return BLK, {"real_work": LANE_FUND_BULK_INVENTORY,
                     "blocker": "NO_HTTP_TRANSPORT",
                     "reason": "no SEC HTTP transport injected",
                     "disposition": "DATA_HOLD"}
    owned_facts = 0
    if callable(ctx.read_normalized):
        try:
            owned_facts = sum(1 for _ in ctx.read_normalized(
                "FUNDAMENTAL_FACT", limit=int(cfg.get("owned_scan_limit",
                                                      2000))))
        except Exception:  # noqa: BLE001 - inventory is best-effort
            owned_facts = 0
    dl = _bulk.BulkArchiveDownloader(
        url=url, dest_dir=final.parent, name="companyfacts",
        headers=_ua_headers(cfg),
        disk_budget_bytes=int(cfg.get("disk_budget_bytes", 4 * 1024 ** 3)),
        transport=ctx.transport)
    budget = float(cfg.get("download_time_budget_seconds", 1800))
    started = _time.monotonic()
    last: dict = {}
    while True:
        last = dl.download_segment()
        if last.get("complete") or not last.get("ok"):
            break
        if (_time.monotonic() - started) >= budget:
            break
    detail = {"real_work": LANE_FUND_BULK_INVENTORY,
              "owned_fundamental_facts_scanned": owned_facts,
              "companyfacts_url": url,
              "download_disposition": last.get("disposition"),
              "progress_pct": last.get("progress_pct"),
              "archive_sha256": last.get("sha256"),
              "archive_bytes": last.get("total_bytes"),
              "archive_exists": final.exists(),
              "complete": bool(last.get("complete")),
              "disposition": "DATA_HOLD", "no_automatic_promotion": True}
    detail["artifact"] = write_artifact(ctx.artifact_root, job.lane, detail,
                                        clock=ctx.clock)
    if last.get("complete"):
        return OK, detail
    detail["reason"] = last.get("reason", "download in progress; resuming")
    return RETRY, detail


def _fund_mapped_cik_plan(ctx: FundamentalJobContext, job) -> tuple:
    """Part 3: derive the resolved historical CIK target set from the canonical
    ACTIVE RESOLVED mappings and seed / append-only-supersede the durable campaign
    cursor. Unresolved securities are EXCLUDED (never a current-survivor
    substitution). The mapped epoch is stamped so the plan re-runs only when the
    resolved mapping changes."""
    OK, BLK, RETRY = _outcomes()
    ciks = _resolved_ciks(ctx)
    if not ciks:
        return BLK, {"real_work": LANE_FUND_MAPPED_CIK_PLAN,
                     "blocker": "NO_RESOLVED_HISTORICAL_CIKS",
                     "reason": ("no ACTIVE RESOLVED security->CIK mapping in the "
                                "identity store; run the Stage 10.1 bridge first"),
                     "disposition": "DATA_HOLD"}
    fingerprint = _hi.content_hash(ciks)
    campaign_id = DEFAULT_CAMPAIGN_ID
    rev = None
    if ctx.campaign_store is not None:
        try:
            rev = ctx.campaign_store.ensure_campaign_revision(
                DEFAULT_CAMPAIGN_ID, kind=CAMPAIGN_KIND, universe=ciks,
                universe_source="stage10_1_resolved_mappings",
                universe_fingerprint=fingerprint,
                batch_size=int(_cfg(ctx).get("cik_batch", 500)))
            campaign_id = rev.get("campaign_id", DEFAULT_CAMPAIGN_ID)
        except Exception as exc:  # noqa: BLE001 - campaign seed never fatal
            rev = {"error": type(exc).__name__}
    ctx.store.set_meta("stage102_mapped_epoch", _mapping_version(ctx))
    ctx.store.set_meta("stage102_campaign_id", campaign_id)
    ctx.store.set_meta("stage102_mapped_cik_count", str(len(ciks)))
    ctx.store.set_meta("stage102_mapped_fingerprint", fingerprint)
    detail = {"real_work": LANE_FUND_MAPPED_CIK_PLAN,
              "mapped_cik_count": len(ciks), "campaign_id": campaign_id,
              "universe_fingerprint": fingerprint, "campaign_revision": rev,
              "sample_ciks": ciks[:10], "disposition": "DATA_HOLD",
              "no_automatic_promotion": True}
    detail["artifact"] = write_artifact(ctx.artifact_root, job.lane, detail,
                                        clock=ctx.clock)
    return OK, detail


def _fund_bulk_index(ctx: FundamentalJobContext, job) -> tuple:
    """Part 2 + 4: stream the companyfacts archive into the durable fact index,
    cataloguing every member (complete, not sampled) and materialising the target
    concepts for the mapped-CIK allowlist. Bounded per step + wall-clock;
    idempotent (facts UNIQUE per cik/tag/unit/period/accession, amendments
    preserved); restart-safe (durable member cursor). Records per-CIK campaign
    progress (attempted/completed/missing)."""
    OK, BLK, RETRY = _outcomes()
    cfg = _cfg(ctx)
    idx = ctx.companyfacts_index
    if idx is None:
        return BLK, {"real_work": LANE_FUND_BULK_INDEX,
                     "blocker": "NO_COMPANYFACTS_INDEX",
                     "reason": "companyfacts index not configured",
                     "disposition": "DATA_HOLD"}
    final, _ = _companyfacts_paths(cfg)
    if final is None or not final.exists():
        return BLK, {"real_work": LANE_FUND_BULK_INDEX,
                     "blocker": "COMPANYFACTS_ARCHIVE_ABSENT",
                     "reason": ("companyfacts.zip not present; run "
                                "fundamentals.bulk_inventory first"),
                     "disposition": "DATA_HOLD"}
    ciks = _resolved_ciks(ctx)
    ahash = _companyfacts_hash(cfg)
    r = idx.index_companyfacts_archive(
        final, archive_hash=ahash, allowlist_ciks=ciks,
        target_tags=_target_tags(ctx),
        member_step=int(cfg.get("index_member_step", 5000)),
        time_budget_seconds=float(cfg.get("index_time_budget_seconds", 1200)))
    # Record per-CIK campaign progress (idempotent; a re-recorded COMPLETED CIK is
    # a no-op). A mapped CIK with no companyfacts member once the archive is fully
    # streamed is an honest MISSING (recorded as failed, exact reason).
    campaign_id = ctx.store.get_meta("stage102_campaign_id") or DEFAULT_CAMPAIGN_ID
    materialized = []
    missing = []
    if ctx.campaign_store is not None:
        for c in ciks:
            m = idx.member(c)
            if m and m.get("materialized"):
                materialized.append(c)
            elif r.get("complete") and (m is None):
                missing.append(c)
        try:
            failed = [(c, "NO_COMPANYFACTS_MEMBER") for c in missing]
            ctx.campaign_store.record_results(
                campaign_id, succeeded=materialized, failed=failed)
            ctx.campaign_store.record_batch(
                campaign_id, run_date=ctx.now()[:10],
                progress=bool(materialized), origin=ORIGIN_102,
                stop_reason=None if r.get("complete") else "IN_PROGRESS",
                metrics={"ciks_completed": len(materialized),
                         "records_added": r.get("facts_indexed"),
                         "issuers_covered": r.get("ciks_materialized")})
        except Exception:  # noqa: BLE001 - campaign bookkeeping never fatal
            pass
    detail = {"real_work": LANE_FUND_BULK_INDEX, "archive_sha256": ahash,
              "allowlist_size": r.get("allowlist_size"),
              "members_done": r.get("members_done"),
              "total_members": r.get("total_members"),
              "members_cataloged": r.get("members_cataloged"),
              "ciks_materialized": r.get("ciks_materialized"),
              "facts_indexed": r.get("facts_indexed"),
              "malformed_members": r.get("malformed_members"),
              "complete": bool(r.get("complete")),
              "mapped_ciks_materialized": len(materialized),
              "mapped_ciks_missing": len(missing),
              "elapsed_seconds": r.get("elapsed_seconds"),
              "disposition": "DATA_HOLD", "no_automatic_promotion": True}
    detail["artifact"] = write_artifact(ctx.artifact_root, job.lane, detail,
                                        clock=ctx.clock)
    return OK, detail


def _build_pit_store(ctx: FundamentalJobContext):
    from . import sec_companyfacts as _cf
    ciks = _resolved_ciks(ctx)
    return _cf.historical_pit_store_from_index(ctx.companyfacts_index, ciks), ciks


def _fund_pit_materialize(ctx: FundamentalJobContext, job) -> tuple:
    """Part 4: build the leakage-safe PIT store from the durable index for the
    resolved historical CIKs and measure the materialised observations + per-
    candidate concept coverage. The durable facts already live in the index
    (filed-date bounded, amendments preserved); this validates + records the
    measured PIT depth. Stamps the epoch flag on success."""
    OK, BLK, RETRY = _outcomes()
    if ctx.companyfacts_index is None:
        return BLK, {"real_work": LANE_FUND_PIT_MATERIALIZE,
                     "blocker": "NO_COMPANYFACTS_INDEX",
                     "reason": "companyfacts index not configured",
                     "disposition": "DATA_HOLD"}
    store, ciks = _build_pit_store(ctx)
    summ = store.coverage_summary()
    per_candidate = {sig: len(store.ciks_with_candidate(sig))
                     for sig in ctx.signals}
    pit_summary = {
        "pit_observations": summ["pit_observations"],
        "distinct_ciks": summ["distinct_ciks"],
        "concepts_present": summ["concepts_present"],
        "availability_start": summ["availability_start"],
        "availability_end": summ["availability_end"],
        "ciks_with_candidate": per_candidate,
        "mapped_ciks": len(ciks)}
    ctx.store.set_meta("stage102_pit_summary", json.dumps(pit_summary))
    ctx.store.set_meta("stage102_pit_complete", _epoch(ctx))
    detail = {"real_work": LANE_FUND_PIT_MATERIALIZE, **pit_summary,
              "disposition": "DATA_HOLD", "no_automatic_promotion": True}
    detail["artifact"] = write_artifact(ctx.artifact_root, job.lane, detail,
                                        clock=ctx.clock)
    return OK, detail


def _fund_coverage_measure(ctx: FundamentalJobContext, job) -> tuple:
    """Part 5: measure per-rebalance PIT readiness for every candidate on the
    survivorship-safe historical universe (identity universe on each date + the
    RESOLVED map + the measured PIT facts). Aggregate current-company counts can
    never unlock — the survivorship denominator + the per-date fact coverage keep
    it honest. Persists a durable readiness snapshot; stamps the epoch flag."""
    OK, BLK, RETRY = _outcomes()
    from . import fundamental_readiness as _fr
    pit_store, _ = _build_pit_store(ctx)
    snapshot = {}
    for sig in ctx.signals:
        rr = _fr.measured_readiness_from_store(
            ctx.store, sig, ctx.cfg9, pit_store=pit_store,
            rebalance_dates=ctx.rebalance_dates, index_name=ctx.index_name)
        snapshot[sig] = {
            "sufficient": rr.get("sufficient"), "blocker": rr.get("blocker"),
            "mapping_available": rr.get("mapping_available"),
            "valid_scored_periods": rr.get("valid_scored_periods"),
            "median_coverage_pct": rr.get("median_coverage_pct"),
            "median_historical_mapping_coverage_pct":
                rr.get("median_historical_mapping_coverage_pct"),
            "min_eligible_names": rr.get("min_eligible_names"),
            "median_eligible_names": rr.get("median_eligible_names"),
            "subperiod_coverage": rr.get("subperiod_coverage"),
            "earliest_usable_formation_date":
                rr.get("earliest_usable_formation_date"),
            "latest_usable_formation_date":
                rr.get("latest_usable_formation_date")}
    ctx.store.set_meta("stage102_readiness_snapshot", json.dumps(snapshot))
    ctx.store.set_meta("stage102_coverage_complete", _epoch(ctx))
    detail = {"real_work": LANE_FUND_COVERAGE_MEASURE,
              "rebalance_dates": len(ctx.rebalance_dates),
              "readiness": snapshot, "disposition": "DATA_HOLD",
              "no_automatic_promotion": True}
    detail["artifact"] = write_artifact(ctx.artifact_root, job.lane, detail,
                                        clock=ctx.clock)
    return OK, detail


def _fund_readiness_recheck(ctx: FundamentalJobContext, job) -> tuple:
    """Part 5/6: re-evaluate the MEASURED mapping status + the MEASURED activation
    gate for every candidate from the measured PIT store. Records the gate result;
    NEVER flips a switch. Stamps the epoch flag on success."""
    OK, BLK, RETRY = _outcomes()
    from . import fundamental_readiness as _fr
    pit_store, _ = _build_pit_store(ctx)
    mapping = _fr.historical_mapping_status_from_store(ctx.store, ctx.cfg9)
    gate = {}
    for sig in ctx.signals:
        g = _fr.historical_fundamental_experiment_allowed(
            ctx.cfg9, store=ctx.store, signal=sig, pit_store=pit_store)
        gate[sig] = {"allowed": g["allowed"], "activation_mode":
                     g["activation_mode"], "mapping_available":
                     g["mapping_available"], "readiness_sufficient":
                     g["readiness_sufficient"], "readiness_blocker":
                     g.get("readiness_blocker"), "diagnostic": g["diagnostic"]}
    ctx.store.set_meta("stage102_gate_snapshot", json.dumps(gate))
    ctx.store.set_meta("stage102_readiness_complete", _epoch(ctx))
    detail = {"real_work": LANE_FUND_READINESS_RECHECK,
              "measured_mapping_available": mapping["available"],
              "measured_mapping_coverage_pct": mapping.get(
                  "measured_coverage_pct"),
              "gate": gate, "safety_switch_flipped": False,
              "disposition": "DATA_HOLD", "no_automatic_promotion": True}
    detail["artifact"] = write_artifact(ctx.artifact_root, job.lane, detail,
                                        clock=ctx.clock)
    return OK, detail


def _fund_activation_recheck(ctx: FundamentalJobContext, job) -> tuple:
    """Part 6/7: record the FINAL measured activation-gate result (OPEN/CLOSED,
    activation mode, exact reason). When OPEN, the tournament tick — not this
    handler — generates the canonical fundamental experiment. Stamps the epoch
    flag; never enqueues an experiment; never flips a switch."""
    OK, BLK, RETRY = _outcomes()
    from . import fundamental_readiness as _fr
    pit_store, _ = _build_pit_store(ctx)
    primary = ctx.signals[0] if ctx.signals else "gross_profitability"
    g = _fr.historical_fundamental_experiment_allowed(
        ctx.cfg9, store=ctx.store, signal=primary, pit_store=pit_store)
    any_open = False
    for sig in ctx.signals:
        gg = _fr.historical_fundamental_experiment_allowed(
            ctx.cfg9, store=ctx.store, signal=sig, pit_store=pit_store)
        any_open = any_open or bool(gg["allowed"])
    ctx.store.set_meta("stage102_activation_open", "1" if any_open else "0")
    ctx.store.set_meta("stage102_activation_complete", _epoch(ctx))
    detail = {"real_work": LANE_FUND_ACTIVATION_RECHECK,
              "activation_mode": g["activation_mode"],
              "activation_open_any_signal": any_open,
              "primary_signal": primary, "primary_allowed": g["allowed"],
              "diagnostic": g["diagnostic"], "reason": g["reason"],
              "note": ("when open, the tournament tick generates the canonical "
                       "fundamental experiment; never enqueued here"),
              "safety_switch_flipped": False, "disposition": "DATA_HOLD",
              "no_automatic_promotion": True}
    detail["artifact"] = write_artifact(ctx.artifact_root, job.lane, detail,
                                        clock=ctx.clock)
    return OK, detail


_LANE_HANDLERS = {
    LANE_FUND_BULK_INVENTORY: _fund_bulk_inventory,
    LANE_FUND_MAPPED_CIK_PLAN: _fund_mapped_cik_plan,
    LANE_FUND_BULK_INDEX: _fund_bulk_index,
    LANE_FUND_PIT_MATERIALIZE: _fund_pit_materialize,
    LANE_FUND_COVERAGE_MEASURE: _fund_coverage_measure,
    LANE_FUND_READINESS_RECHECK: _fund_readiness_recheck,
    LANE_FUND_ACTIVATION_RECHECK: _fund_activation_recheck,
}


def dispatch_fundamental_job(job, ctx: FundamentalJobContext) -> tuple:
    """Dispatch ONE claimed Stage 10.2 job to its lane handler. Bounded, idempotent
    (a job already recorded in the identity store's processed_jobs is a no-op
    COMPLETED), restart-safe and failure-isolated (a handler exception becomes a
    bounded RETRYABLE — never crashes the drain). Returns (outcome, detail)."""
    from . import autonomous_research as _ar
    lane = str(getattr(job, "lane", ""))
    handler = _LANE_HANDLERS.get(lane)
    if handler is None:
        return _ar.OUTCOME_BLOCKED_SPECIFIC, {
            "reason": "no fundamental handler for lane %s" % lane}
    job_key = "%s:%s" % (lane, _hi.content_hash(job.payload or {})[:16])
    if ctx.store.already_processed(job_key):
        return _ar.OUTCOME_COMPLETED, {"real_work": lane,
                                       "idempotent_skip": True,
                                       "disposition": "DATA_HOLD"}
    try:
        outcome, detail = handler(ctx, job)
    except Exception as exc:  # noqa: BLE001 - never crash the drain
        return _ar.OUTCOME_RETRYABLE, {
            "reason": "fundamental handler raised: %s" % type(exc).__name__,
            "lane": lane}
    if outcome == _ar.OUTCOME_COMPLETED:
        ctx.store.mark_processed(job_key, job_id=getattr(job, "job_id", None),
                                 kind=lane)
    detail.setdefault("lane", lane)
    return outcome, detail


# --------------------------------------------------------------------------- #
# Autonomous dependency planner. The AlphaAgent generates its OWN next Stage 10.2
# job: it inspects the download / index / campaign / readiness state, picks the
# single highest-value next action and enqueues exactly one idempotent job (at
# most one live fundamental job at a time).
# --------------------------------------------------------------------------- #
def _has_live_fundamental_job(queue) -> bool:
    from . import autonomous_research as _ar
    for st in (_ar.STATE_QUEUED, _ar.STATE_RUNNING, _ar.STATE_RETRYABLE):
        for j in queue.list_jobs(state=st, limit=1000):
            if str(j.lane).startswith(FUNDAMENTAL_LANE_PREFIX) and \
                    j.origin == ORIGIN_102:
                return True
    return False


def _enqueue102(queue, ctx: FundamentalJobContext, lane: str, category: str,
                reason: str, payload: dict, *,
                max_attempts: Optional[int] = None) -> dict:
    from . import autonomous_research as _ar  # noqa: F401 - parity import
    p = dict(payload or {})
    p["prioritization_reason"] = reason
    p["planned_at"] = ctx.now()
    p["stage"] = "10.2"
    pr = int((ctx.stage102 or {}).get("priority", DEFAULT_PRIORITY))
    job_id = queue.enqueue(category, lane=lane, payload=p, priority=pr,
                           origin=ORIGIN_102, max_attempts=max_attempts)
    ctx.store.set_meta("last_stage102_reason", "%s | %s" % (lane, reason))
    return {"job_id": job_id, "lane": lane, "category": category,
            "reason": reason, "origin": ORIGIN_102, "payload": p}


def _plan_stage102(queue, ctx: FundamentalJobContext) -> Optional[dict]:
    """Drive the Stage 10.2 campaign in strict dependency order: download
    companyfacts.zip -> plan the mapped-CIK target set -> stream the fact index ->
    materialise PIT -> measure per-rebalance readiness -> re-check the measured
    activation gate. Returns the SINGLE highest-value next step, or None when the
    whole downstream path is measured for the current epoch (so the tournament /
    identity / companyfacts reclaim the slot). The AlphaAgent — not Claude —
    generates each next action, and (when the gate opens) the tournament tick
    generates the fundamental experiment."""
    from . import autonomous_research as _ar
    cfg = _cfg(ctx)
    idx = ctx.companyfacts_index
    # 1) Acquire the SEC companyfacts bulk archive (restart-safe download).
    final, _ = _companyfacts_paths(cfg)
    if final is None or not final.exists():
        return _enqueue102(
            queue, ctx, LANE_FUND_BULK_INVENTORY, _ar.CAT_DATA_ACQUISITION,
            "SEC companyfacts bulk archive not yet acquired; download it "
            "(restart-safe, atomic, SHA-256)", {"stage": "download"},
            max_attempts=int(cfg.get("download_max_attempts", 24)))
    # 2) Derive the resolved mapped-CIK target set + seed the durable campaign.
    mvh = _mapping_version(ctx)
    if (ctx.store.get_meta("stage102_mapped_epoch") or "") != mvh:
        return _enqueue102(
            queue, ctx, LANE_FUND_MAPPED_CIK_PLAN, _ar.CAT_DATA_ACQUISITION,
            "derive the resolved historical CIK target set + seed the durable "
            "companyfacts campaign cursor", {"mapping_version": mvh})
    # 3) Stream the companyfacts archive into the durable fact index.
    st = idx.archive_status("companyfacts") if idx is not None else {}
    if not st.get("complete"):
        return _enqueue102(
            queue, ctx, LANE_FUND_BULK_INDEX, _ar.CAT_DATA_ACQUISITION,
            "companyfacts fact index incomplete: %s/%s members streamed"
            % (st.get("members_done", 0), st.get("total_members", 0)),
            {"members_done": st.get("members_done", 0),
             "total_members": st.get("total_members", 0),
             "facts_indexed": st.get("facts_indexed", 0)},
            max_attempts=int(cfg.get("index_max_attempts", 48)))
    # 4-7) Materialise PIT, measure readiness, re-check the activation gate —
    #      each ONCE per epoch (the HANDLER stamps the epoch flag on success).
    epoch = _epoch(ctx)
    if ctx.store.get_meta("stage102_pit_complete") != epoch:
        return _enqueue102(
            queue, ctx, LANE_FUND_PIT_MATERIALIZE, _ar.CAT_DATA_VALIDATION,
            "materialise leakage-safe PIT observations for the resolved "
            "historical CIKs from the bulk index", {"epoch": epoch})
    if ctx.store.get_meta("stage102_coverage_complete") != epoch:
        return _enqueue102(
            queue, ctx, LANE_FUND_COVERAGE_MEASURE, _ar.CAT_DATA_VALIDATION,
            "measure per-rebalance PIT readiness for every candidate on the "
            "survivorship-safe historical universe", {"epoch": epoch})
    if ctx.store.get_meta("stage102_readiness_complete") != epoch:
        return _enqueue102(
            queue, ctx, LANE_FUND_READINESS_RECHECK, _ar.CAT_DATA_VALIDATION,
            "re-evaluate measured mapping + measured activation gate from "
            "canonical state", {"epoch": epoch})
    if ctx.store.get_meta("stage102_activation_complete") != epoch:
        return _enqueue102(
            queue, ctx, LANE_FUND_ACTIVATION_RECHECK, _ar.CAT_DATA_VALIDATION,
            "record the final measured activation-gate result (the tournament "
            "generates the experiment when open)", {"epoch": epoch})
    return None


def plan_next_fundamental_job(queue, ctx: FundamentalJobContext, *,
                              cfg: Optional[dict] = None) -> Optional[dict]:
    """Determine and enqueue the SINGLE highest-value next Stage 10.2 action, or
    return None when the downstream campaign is measured for the current epoch (so
    the queue is never flooded and the tournament is never permanently starved). At
    most ONE live fundamental job exists at a time (idempotent). Driven only when
    Stage 10.2 is enabled AND the companyfacts index exists."""
    cfg = cfg or ctx.stage102 or {}
    if not cfg.get("enabled") or not cfg.get("planner_enabled", True):
        return None
    if ctx.companyfacts_index is None:
        return None
    if _has_live_fundamental_job(queue):
        return None
    return _plan_stage102(queue, ctx)


__all__ = [
    "ORIGIN_102", "FUNDAMENTAL_LANE_PREFIX",
    "LANE_FUND_BULK_INVENTORY", "LANE_FUND_MAPPED_CIK_PLAN",
    "LANE_FUND_BULK_INDEX", "LANE_FUND_PIT_MATERIALIZE",
    "LANE_FUND_COVERAGE_MEASURE", "LANE_FUND_READINESS_RECHECK",
    "LANE_FUND_ACTIVATION_RECHECK", "FundamentalJobContext",
    "dispatch_fundamental_job", "plan_next_fundamental_job", "DEFAULT_PRIORITY",
    "DEFAULT_CAMPAIGN_ID", "CAMPAIGN_KIND",
]
